name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        platforms: linux/arm64, linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_REPOSITORY_BACKEND }}:latest
          ${{ secrets.DOCKER_REPOSITORY_BACKEND }}:${{ github.sha }}

    - name: Verify Backend Docker Hub
      run: docker pull ${{ secrets.DOCKER_REPOSITORY_BACKEND }}:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend/my-counter-app
        file: ./frontend/my-counter-app/Dockerfile
        platforms: linux/arm64, linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_REPOSITORY_FRONTEND }}:latest
          ${{ secrets.DOCKER_REPOSITORY_FRONTEND }}:${{ github.sha }}

    - name: Verify Frontend Docker Hub
      run: docker pull ${{ secrets.DOCKER_REPOSITORY_FRONTEND }}:${{ github.sha }} 

  update-manifest:
    runs-on: ubuntu-latest
    needs: 
      - build-backend
      - build-frontend

    steps:
    - name: Checkout k8s-manifest-repo
      run: |
        git clone https://github.com/mochangil/k8s-manifest-boilerplate
        cd k8s-manifest-boilerplate

        sed -i "s|newTag: .*|newTag: \${{ github.sha }}|g" backend/overlays/dev/kustomization.yml
        sed -i "s|newTag: .*|newTag: \${{ github.sha }}|g" frontend/overlays/dev/kustomization.yml

        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Update image to mo991207/counter-springboot-app:${{ github.sha }}"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mochangil/k8s-manifest-boilerplate
